# Generated by Django 5.0.6 on 2024-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
